---
# tasks file for wordpress

- name: Download WordPress 
  get_url: 
     url: https://wordpress.org/latest.tar.gz 
     dest: /tmp/wordpress.tar.gz
  sudo: yes

- name: Create Wordpress Folder
  file: 
    path: /var/www/wordpress_alex 
    state: directory
  sudo: yes

- name: Extract WordPress  
  unarchive: 
      src: /tmp/wordpress.tar.gz 
      dest: /var/www/wordpress_alex
      copy: no 
  sudo: yes

- name: Move foo to bar
  command: mv /var/www/wordpress_alex/wordpress/* /var/www/wordpress_alex
